// FPS and esports slang for the glossary page. Keep definitions short, factual
// and in British English.
export default [
  { term: "Frag", def: "To kill another player in a multiplayer game, or the kill itself. The word comes from military slang for an attack with a fragmentation grenade and was popularised by Doom and Quake in the 1990s, where the scoreboard counted frags." },
  { term: "Frag limit", def: "The number of kills that ends a deathmatch. The first player to reach it wins the map." },
  { term: "Frag movie", def: "An edited video of a player's or team's best kills, usually cut to music. Frag movies grew out of the Quake and Counter-Strike scenes in the late 1990s and early 2000s and are the ancestors of today's highlight reels." },
  { term: "Frag grenade", def: "A fragmentation grenade, which deals damage in an area when it explodes. Many shooters name their standard grenade this way." },
  { term: "Fragger", def: "A player whose main job is getting kills. In Counter-Strike an entry fragger is the first player into a site, trading their life for space and information." },
  { term: "Entry frag", def: "The first kill of a round, usually made by the player leading an attack into a bombsite or objective." },
  { term: "Deathmatch", def: "A mode where every player fights every other player and the winner is the one with the most frags. Team deathmatch splits players into sides." },
  { term: "K/D ratio", def: "Kills divided by deaths. A K/D above 1.0 means a player gets more frags than they give up." },
  { term: "Ace", def: "One player killing all five members of the enemy team in a single round, a term used in Counter-Strike, Valorant and other five-a-side shooters." },
  { term: "Clutch", def: "Winning a round as the last player alive on your team, often against several opponents. A one versus three clutch is written 1v3." },
  { term: "Multikill", def: "Several kills in quick succession. Unreal Tournament announced them as double kill, multi kill, mega kill, ultra kill, monster kill and so on." },
  { term: "Killing spree", def: "A run of kills without dying. Unreal Tournament's announcer made phrases such as rampage, dominating, unstoppable and godlike famous." },
  { term: "Headshot", def: "A shot to an opponent's head, which deals extra damage in most shooters and kills instantly with many weapons." },
  { term: "One tap", def: "A kill with a single bullet, usually a headshot with a rifle or pistol." },
  { term: "Spray", def: "Holding down the trigger on an automatic weapon. A spray pattern is the fixed path the recoil follows, which skilled players learn to control." },
  { term: "Flick", def: "A fast, precise mouse movement that snaps the crosshair onto a target." },
  { term: "Wallbang", def: "Shooting an opponent through a wall, door or other surface that bullets can pass through." },
  { term: "Noscope", def: "Hitting a shot with a sniper rifle without looking through the scope." },
  { term: "Rocket jump", def: "Firing a rocket at your feet to launch yourself higher or further than a normal jump, at the cost of some health. A core movement skill in Quake." },
  { term: "Strafe jumping", def: "A movement technique in Quake and similar engines that builds speed by combining strafing, mouse turning and jumping." },
  { term: "Rail", def: "Short for the railgun, a hitscan weapon in Quake that rewards precise aim. Landing one at long range is a classic frag movie moment." },
  { term: "Spawn kill", def: "Killing a player as soon as they respawn, before they have a chance to react. Often seen as poor sportsmanship." },
  { term: "Camping", def: "Staying in one spot and waiting for opponents to come to you, rather than moving around the map." },
  { term: "Trade", def: "Killing the opponent who has just killed your teammate, so the exchange ends even." },
  { term: "Eco round", def: "In Counter-Strike and Valorant, a round where a team spends little or nothing so it can afford full equipment later." },
  { term: "Pick", def: "An early kill that gives a team a numbers advantage before the main fight starts." },
  { term: "Hitscan", def: "A weapon whose shots hit instantly along the line of aim, with no travel time. Most rifles are hitscan; rockets and grenades are projectiles." },
  { term: "LAN", def: "A local area network. A LAN event or LAN party is where players bring their computers to the same place, which removes online lag and is how most major tournaments are played." },
  { term: "GG", def: "Good game. Typed at the end of a match as a sign of sportsmanship." },
  { term: "Tick rate", def: "How many times per second a game server updates the game state. A higher tick rate makes hit registration more accurate." },
  { term: "Peeker's advantage", def: "The small edge a player moving round a corner has over a player holding still, caused by network delay." },
  { term: "Smurf", def: "An experienced player using a new or low-ranked account to play against weaker opponents." },
];
