// YouTube videos shown on the home and videos pages. Each id was checked with
// YouTube's oEmbed endpoint, which only answers for videos that exist and
// allow embedding. group is a key from videoGroups.js. The video marked
// featured is shown large at the top of the home page. Update
// site.videosChecked when you recheck them.
export default [
  {
    id: "cRV0tclxXMQ",
    group: "classic",
    featured: true,
    title: "Ultimate Quake Frag Video - AnnihilatioN HQ",
    channel: "SyNcHroToN",
    game: "Quake III Arena",
    blurb: "A high quality upload of AnnihilatioN, one of the best known Quake III Arena frag movies: a fast montage of rocket, rail and lightning gun frags set to music.",
  },
  {
    id: "0OCDE7Dm6Fo",
    group: "classic",
    title: "Quake Live | COOLLER - 60FPS [Frag Movie]",
    channel: "WASD - The Home of Frag Movies",
    game: "Quake Live",
    blurb: "A 60fps frag movie of Anton \"Cooller\" Singov, one of the most decorated Quake duel players, showing his aim and item control in Quake Live.",
  },
  {
    id: "Leqjjq-mVqA",
    group: "classic",
    title: "UT2004 Fragmovie: EDGE2 by F51",
    channel: "F51",
    game: "Unreal Tournament 2004",
    blurb: "EDGE2 is an Unreal Tournament 2004 frag movie uploaded by its creator, full of shock rifle combos and lightning gun frags set to music.",
  },
  {
    id: "w1QYD8Dz2FE",
    group: "classic",
    title: "What I found by watching a twenty-year-old Doom II deathmatch",
    channel: "Alistair Roche",
    game: "Doom II",
    blurb: "A video essay that breaks down a two-decade-old Doom II deathmatch recording, explaining the movement, map knowledge and weapon choices behind each frag.",
  },
  {
    id: "XJyqQW1sdk0",
    group: "counter-strike",
    title: "MLG Columbus 2016: coldzera vs. Liquid [AWP 4k w/ jump shot]",
    channel: "HLTVorg",
    game: "CS:GO",
    year: 2016,
    blurb: "Coldzera's AWP four-kill against Team Liquid on Mirage at the MLG Columbus Major, including the jumping double kill that became one of the best known plays in Counter-Strike.",
  },
  {
    id: "2xvrX0U8FkE",
    group: "counter-strike",
    title: "ESL One Cologne 2016: Liquid s1mple 1 vs 2 Fnatic Dropping No Scope AWP Double Clutch on de_cache",
    channel: "ESEA",
    game: "CS:GO",
    year: 2016,
    blurb: "S1mple, playing for Team Liquid, wins a 1v2 against Fnatic on Cache, finishing it with a no-scope AWP shot while dropping off a ledge.",
  },
  {
    id: "oYqh_jfJU3I",
    group: "counter-strike",
    title: "The Controversial Olofboost",
    channel: "theScore esports",
    game: "CS:GO",
    year: 2014,
    blurb: "The story of the olofboost, the Overpass boost Fnatic used against LDLC at DreamHack Winter 2014, and the backlash that led Fnatic to forfeit.",
  },
  {
    id: "xdstSkyavew",
    group: "counter-strike",
    title: "BEST MOMENTS of IEM Cologne Major 2026 Playoffs | CS2",
    channel: "ESL Counter-Strike Highlights",
    game: "Counter-Strike 2",
    year: 2026,
    blurb: "ESL's official compilation of the best frags, clutches and multikills from the playoffs of the IEM Cologne Major 2026.",
  },
  {
    id: "AuZ5vf0rLx8",
    group: "modern",
    title: "Best VALORANT ACEs in 5 Years",
    channel: "VALORANT Champions Tour",
    game: "Valorant",
    blurb: "The official VCT channel collects the best aces from five years of professional Valorant: rounds where one player eliminates the entire enemy team.",
  },
  {
    id: "5M5D_vD4Lxw",
    group: "modern",
    title: "The Most Iconic Plays From Year 4 of ALGS",
    channel: "Apex Legends Global Series",
    game: "Apex Legends",
    blurb: "Standout fights, squad wipes and final circle plays from the fourth year of the Apex Legends Global Series, from the official ALGS channel.",
  },
  {
    id: "TMMOnhOv_fw",
    group: "modern",
    title: "Top 10 Clutch Plays In OWL History",
    channel: "Overwatch Esports",
    game: "Overwatch",
    blurb: "The official Overwatch Esports channel counts down ten of the best clutch plays in Overwatch League history.",
  },
  {
    id: "4Mg01kyw1xc",
    group: "modern",
    title: "Highlights: beastcoast vs. Team Liquid - BLAST R6 Manchester Major // Semifinal",
    channel: "Rainbow Six Esports",
    game: "Rainbow Six Siege",
    year: 2024,
    blurb: "Official highlights of the semi-final between beastcoast and Team Liquid at the BLAST R6 Manchester Major.",
  },
  {
    id: "12oT2Kg8Tk8",
    group: "history",
    title: "The Hook That Nobody Escapes: The Story of Thresh",
    channel: "theScore esports",
    game: "Quake",
    blurb: "Dennis \"Thresh\" Fong, often called the first professional esports player, and his 1997 Red Annihilation win, where the prize was John Carmack's Ferrari.",
  },
  {
    id: "OipJYWhMi3k",
    group: "history",
    title: "RetroAhoy: Quake",
    channel: "Ahoy",
    game: "Quake",
    blurb: "Ahoy's documentary on the making and influence of id Software's Quake, covering its technology, design and lasting effect on multiplayer shooters.",
  },
  {
    id: "aUPcngRGnu8",
    group: "history",
    title: "The History of Quake with Tim Willits",
    channel: "/noclip",
    game: "Quake",
    blurb: "Former id Software studio director Tim Willits talks through the history of the Quake series with the documentary team at /noclip.",
  },
];
